/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_ma_jni_AClass */

#ifndef _Included_com_ma_jni_AClass
#define _Included_com_ma_jni_AClass
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
