/* DO NOT EDIT THIS FILE - it is machine generated */
#include "TestJNIString.h"
#include "MyJniLog.h"
#include <stdlib.h>
#include <string.h>

JNIEXPORT jstring JNICALL Java_com_ma_jni_TestJNIString_sayHello
        (JNIEnv *env, jobject thisObj, jstring inJNIStr) {
// Step 1: Convert the JNI String (jstring) into C-String (char*)
    const char *inCStr = (env)->GetStringUTFChars(inJNIStr, NULL);
    if (NULL == inCStr) return NULL;

// Step 2: Perform its intended operations
    LOGI("In C, the received string is: %s\n", inCStr);
    (env)->ReleaseStringUTFChars(inJNIStr, inCStr);  // release resources

// Prompt user for a C-string
    const char *outCStr = "C string here";
    //  or
    //  string outCppStr = "C++ string UTF-8 strings";
    // Step X: Convert the C++ string to C-string, then to JNI String (jstring) and return
    // return env->NewStringUTF(outCppStr.c_str());

// Step 3: Convert the C-string (char*) into JNI String (jstring) and return
    return (env)->NewStringUTF(outCStr);
}