/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_ma_jni_TestJNIInstanceVariable */

#ifndef _Included_com_ma_jni_TestJNIInstanceVariable
#define _Included_com_ma_jni_TestJNIInstanceVariable
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_ma_jni_TestJNIInstanceVariable
 * Method:    modifyInstanceVariable
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_ma_jni_TestJNIInstanceVariable_modifyInstanceVariable
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
