/* DO NOT EDIT THIS FILE - it is machine generated */
#include "TestJNIPrimitive.h"
#include "MyJniLog.h"
/* Header for class com_ma_jni_TestJNIPrimitive */


JNIEXPORT jdouble JNICALL Java_com_ma_jni_TestJNIPrimitive_average
        (JNIEnv *env, jobject obj, jint n1, jint n2) {
  jdouble result;
  LOGI("In C++, the numbers are n1= %d  and n2 = %d",n1 ,n2);
  result = ((jdouble)n1 + n2) / 2.0;
  // jint is mapped to int, jdouble is mapped to double
  return result;
}
