/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_ma_jni_TestJNIStaticVariable */

#ifndef _Included_com_ma_jni_TestJNIStaticVariable
#define _Included_com_ma_jni_TestJNIStaticVariable
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_ma_jni_TestJNIStaticVariable
 * Method:    modifyStaticVariable
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_ma_jni_TestJNIStaticVariable_modifyStaticVariable
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
