/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_ma_jni_TestJNIObjectArray */

#ifndef _Included_com_ma_jni_TestJNIObjectArray
#define _Included_com_ma_jni_TestJNIObjectArray
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_ma_jni_TestJNIObjectArray
 * Method:    sumAndAverage
 * Signature: ([Ljava/lang/Integer;)[Ljava/lang/Double;
 */
JNIEXPORT jobjectArray JNICALL Java_com_ma_jni_TestJNIObjectArray_sumAndAverage
  (JNIEnv *, jobject, jobjectArray);

#ifdef __cplusplus
}
#endif
#endif
