/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_ma_jni_TestJNICallBackMethod */

#ifndef _Included_com_ma_jni_TestJNICallBackMethod
#define _Included_com_ma_jni_TestJNICallBackMethod
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_ma_jni_TestJNICallBackMethod
 * Method:    nativeMethod
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_ma_jni_TestJNICallBackMethod_nativeMethod
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
