/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_ma_jni_TestJNIConstructor */

#ifndef _Included_com_ma_jni_TestJNIConstructor
#define _Included_com_ma_jni_TestJNIConstructor
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_ma_jni_TestJNIConstructor
 * Method:    getIntegerObject
 * Signature: (I)Ljava/lang/Integer;
 */
JNIEXPORT jobject JNICALL Java_com_ma_jni_TestJNIConstructor_getIntegerObject
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
